// 이학적 검사 라이브러리 — 부위별 검사 목록
// 환자는 region으로 해당 부위 검사 + 공통 검사를 사용한다.

const EXAM_LIBRARY = {
  common: [
    { id: 'obs_posture', name: '자세 관찰', cat: '시진' },
    { id: 'obs_gait', name: '보행 관찰', cat: '시진' },
    { id: 'obs_swelling', name: '부종·변형·피부 관찰', cat: '시진' },
    { id: 'vital', name: '활력징후 측정', cat: '기본' },
    { id: 'pain_scale', name: '통증 척도 평가 (NRS/VAS)', cat: '기본' },
  ],
  cervical: [
    { id: 'c_arom', name: '목뼈(경추) 능동관절가동범위 (AROM)', cat: 'ROM' },
    { id: 'c_prom', name: '목뼈 수동관절가동범위 (PROM)', cat: 'ROM' },
    { id: 'c_seg_mob', name: '목뼈 분절 가동성 검사 (PA glide)', cat: '촉진' },
    { id: 'c_palpation', name: '목뼈·위등세모근(상부승모근) 촉진', cat: '촉진' },
    { id: 'spurling', name: 'Spurling 검사', cat: '특수검사' },
    { id: 'distraction', name: '목뼈 견인 검사 (Distraction test)', cat: '특수검사' },
    { id: 'ultt', name: '팔신경긴장검사 (ULTT)', cat: '신경학적' },
    { id: 'c_neuro', name: '팔 신경학적 검사 (감각·반사·근력)', cat: '신경학적' },
    { id: 'cfrt', name: '목뼈 굽힘(굴곡)-돌림(회전) 검사 (CFRT — 목인성(경인성) 두통 감별)', cat: '특수검사' },
    { id: 'ccft', name: '머리목굽힘검사(두개경부굴곡검사) (CCFT)', cat: '기능' },
    { id: 'nfme', name: '목 굽힘근 지구력 검사 (Neck flexor endurance)', cat: '기능' },
    { id: 'hit6', name: '두통 영향 검사 (HIT-6) 설문', cat: '설문' },
    { id: 'ndi', name: '목장애지수(경부장애지수) (NDI) 설문', cat: '설문' },
    { id: 'psfs_c', name: '환자 특정 기능 척도 (PSFS)', cat: '설문' },
    { id: 'vbi', name: '척추기저동맥부전 선별검사', cat: '안전성' },
    { id: 'sharp_purser', name: 'Sharp-Purser 검사 (인대 안정성)', cat: '안전성' },
  ],
  shoulder: [
    { id: 'sh_arom', name: '어깨 능동관절가동범위 (AROM)', cat: 'ROM' },
    { id: 'sh_prom', name: '어깨 수동관절가동범위 (PROM)', cat: 'ROM' },
    { id: 'sh_mmt', name: '어깨 도수근력검사 (MMT)', cat: '근력' },
    { id: 'sh_palpation', name: '어깨 촉진', cat: '촉진' },
    { id: 'neer', name: 'Neer 충돌 검사', cat: '특수검사' },
    { id: 'hawkins', name: 'Hawkins-Kennedy 검사', cat: '특수검사' },
    { id: 'empty_can', name: 'Empty can (Jobe) 검사', cat: '특수검사' },
    { id: 'speed', name: 'Speed 검사', cat: '특수검사' },
    { id: 'apprehension', name: '앞쪽 불안정성 검사 (Apprehension)', cat: '특수검사' },
    { id: 'sh_glide', name: '오목위팔관절(관절와상완관절) 부속 가동성 검사 (joint play)', cat: '촉진' },
    { id: 'c_screen_sh', name: '목뼈(경추) 선별검사 (연관통 배제)', cat: '선별' },
    { id: 'dash', name: 'DASH/SPADI 설문', cat: '설문' },
  ],
  lumbar: [
    { id: 'l_arom', name: '허리뼈(요추) 능동관절가동범위 (AROM)', cat: 'ROM' },
    { id: 'l_seg_mob', name: '허리뼈 분절 가동성 검사 (PA glide)', cat: '촉진' },
    { id: 'l_palpation', name: '허리뼈 주변 촉진', cat: '촉진' },
    { id: 'slr', name: '다리곧게올림(하지직거상) 검사 (SLR)', cat: '신경학적' },
    { id: 'crossed_slr', name: '교차 다리곧게올림 검사', cat: '신경학적' },
    { id: 'slump', name: 'Slump 검사', cat: '신경학적' },
    { id: 'l_neuro', name: '다리 신경학적 검사 (감각·반사·근력)', cat: '신경학적' },
    { id: 'prone_instability', name: '엎드린 자세 불안정성 검사', cat: '특수검사' },
    { id: 'aberrant_motion', name: '굽힘(굴곡)-폄(신전) 동작 질 관찰 (aberrant motion)', cat: '기능' },
    { id: 'centralization', name: '반복운동 검사 (방향선호도/중심화)', cat: '기능' },
    { id: 'faber_l', name: 'FABER 검사 (엉치엉덩관절(천장관절)/엉덩관절(고관절) 선별)', cat: '선별' },
    { id: 'odi', name: '오스웨스트리 장애지수 (ODI) 설문', cat: '설문' },
    { id: 'fabq', name: '공포회피신념 설문 (FABQ)', cat: '설문' },
  ],
  hip: [
    { id: 'h_arom', name: '엉덩관절(고관절) 능동관절가동범위 (AROM)', cat: 'ROM' },
    { id: 'h_prom', name: '엉덩관절 수동관절가동범위 (PROM)', cat: 'ROM' },
    { id: 'h_mmt', name: '엉덩관절 도수근력검사 (MMT)', cat: '근력' },
    { id: 'faber', name: 'FABER (Patrick) 검사', cat: '특수검사' },
    { id: 'fadir', name: 'FADIR 충돌 검사', cat: '특수검사' },
    { id: 'scour', name: 'Scour 검사', cat: '특수검사' },
    { id: 'trendelenburg', name: 'Trendelenburg 검사', cat: '특수검사' },
    { id: 'thomas', name: 'Thomas 검사 (굽힘구축(굴곡구축))', cat: '특수검사' },
    { id: 'dial_test', name: '엉덩관절 dial 검사 (돌림(회전) 불안정성)', cat: '특수검사' },
    { id: 'beighton', name: 'Beighton 전신 과가동성 점수', cat: '시진' },
    { id: 'h_palpation', name: '엉덩관절·샅고랑부위(서혜부) 촉진', cat: '촉진' },
    { id: 'l_screen_h', name: '허리뼈(요추) 선별검사 (연관통 배제)', cat: '선별' },
    { id: 'six_mwt', name: '6분 보행검사', cat: '기능' },
    { id: 'h_perf', name: '신체수행능력 검사 (30초 의자 일어서기·TUG·계단 테스트)', cat: '기능' },
    { id: 'h_balance', name: '균형·낙상위험 평가 (한발서기·4단계 스텝검사)', cat: '기능' },
    { id: 'harris', name: 'Harris Hip Score / HOOS / WOMAC 설문', cat: '설문' },
  ],
  wrist: [
    { id: 'w_arom', name: '손목·수지 관절가동범위 (AROM/PROM)', cat: 'ROM' },
    { id: 'katz', name: 'Katz 손 다이어그램 (증상 분포도)', cat: '기본' },
    { id: 'wrist_ratio', name: '손목 비율 지수 측정 (wrist ratio index)', cat: '기본' },
    { id: 'swmt', name: 'Semmes-Weinstein 모노필라멘트 검사 (SWMT)', cat: '신경학적' },
    { id: 'two_pd', name: '2점 식별 검사 (static 2-point discrimination)', cat: '신경학적' },
    { id: 'ultt_w', name: '팔신경긴장검사 (ULTT — 정중신경)', cat: '신경학적' },
    { id: 'phalen', name: 'Phalen 검사', cat: '특수검사' },
    { id: 'tinel_w', name: 'Tinel 징후 (손목 정중신경)', cat: '특수검사' },
    { id: 'carpal_comp', name: '손목굴(수근관) 압박 검사 (carpal compression/Durkan)', cat: '특수검사' },
    { id: 'thenar', name: '엄지두덩(무지구) 관찰·APB 근력검사 (엄지벌림근)', cat: '근력' },
    { id: 'grip_pinch', name: '악력·집기 근력 검사 (grip/3-point pinch)', cat: '근력' },
    { id: 'dexterity', name: '손 기민성 검사 (Purdue Pegboard/Moberg pick-up)', cat: '기능' },
    { id: 'c_screen_w', name: '목뼈(경추) 선별검사 (목뼈 신경뿌리병증(신경근병증) 배제)', cat: '선별' },
    { id: 'ctq', name: 'Boston CTQ 설문 (증상 중증도 SSS·기능 FS) / DASH', cat: '설문' },
  ],
  knee: [
    { id: 'k_arom', name: '무릎 능동관절가동범위 (AROM)', cat: 'ROM' },
    { id: 'k_prom', name: '무릎 수동관절가동범위 (PROM)', cat: 'ROM' },
    { id: 'k_mmt', name: '무릎 도수근력검사 (MMT)', cat: '근력' },
    { id: 'hip_strength_k', name: '엉덩관절(고관절) 근력 검사 (벌림근·가쪽돌림근)', cat: '근력' },
    { id: 'k_effusion', name: '무릎 삼출액 검사 (Stroke test)', cat: '시진' },
    { id: 'jointline', name: '관절선 압통 촉진', cat: '촉진' },
    { id: 'mcmurray', name: 'McMurray 검사', cat: '특수검사' },
    { id: 'thessaly', name: 'Thessaly 검사', cat: '특수검사' },
    { id: 'lachman', name: 'Lachman 검사', cat: '특수검사' },
    { id: 'ant_drawer_k', name: '앞쪽전위 검사 (Anterior drawer)', cat: '특수검사' },
    { id: 'pivot_shift', name: 'Pivot shift 검사', cat: '특수검사' },
    { id: 'valgus_varus', name: '외반/내반 스트레스 검사', cat: '특수검사' },
    { id: 'pfp_squat', name: '스쿼트 통증 재현 검사 (무릎넙다리(슬개대퇴) 부하 검사)', cat: '특수검사' },
    { id: 'patellar_tilt', name: '무릎뼈(슬개골) 기울임 검사 (patellar tilt)', cat: '특수검사' },
    { id: 'patellar_mob', name: '무릎뼈 가동성·유발 검사 (glide/compression)', cat: '특수검사' },
    { id: 'muscle_length_k', name: '다리 근육 길이 검사 (햄스트링·넙다리네갈래근(대퇴사두근)·장딴지·ITB)', cat: 'ROM' },
    { id: 'step_down', name: '스텝다운·한발 스쿼트 검사 (동적 외반 관찰)', cat: '기능' },
    { id: 'hop_test', name: '한발뛰기 검사 배터리 (single/crossover/triple/6m timed hop)', cat: '기능' },
    { id: 'ikdc', name: 'IKDC / KOOS 설문', cat: '설문' },
    { id: 'akps', name: 'AKPS / KOOS-PF 설문 (앞쪽 무릎통증 척도)', cat: '설문' },
    { id: 'acl_rsi', name: 'ACL-RSI 설문 (부상 후 스포츠 복귀 심리 준비도)', cat: '설문' },
  ],
  ankle: [
    { id: 'a_arom', name: '발목 능동관절가동범위 (AROM)', cat: 'ROM' },
    { id: 'a_prom', name: '발목 수동관절가동범위 (PROM)', cat: 'ROM' },
    { id: 'a_mmt', name: '발목 도수근력검사 (MMT)', cat: '근력' },
    { id: 'a_palpation', name: '발목·발꿈치힘줄(아킬레스건) 촉진', cat: '촉진' },
    { id: 'ottawa', name: '오타와 발목 규칙 (골절 선별)', cat: '안전성' },
    { id: 'ant_drawer_a', name: '발목 앞쪽전위 검사', cat: '특수검사' },
    { id: 'talar_tilt', name: '목말뼈(거골) 기울임 검사 (Talar tilt)', cat: '특수검사' },
    { id: 'thompson', name: 'Thompson 검사 (발꿈치힘줄 파열)', cat: '특수검사' },
    { id: 'arc_sign', name: 'Arc sign / Royal London 검사', cat: '특수검사' },
    { id: 'heel_raise', name: '한발 뒤꿈치 들기 검사', cat: '기능' },
    { id: 'balance_test', name: '한발 서기 균형검사 (BESS/SEBT)', cat: '기능' },
    { id: 'figure8', name: '부종 둘레 측정 (figure-of-8)', cat: '시진' },
    { id: 'faam', name: '발·발목 기능척도 (FAAM) 설문', cat: '설문' },
    { id: 'visa_a', name: 'VISA-A 설문 (발꿈치힘줄병증(아킬레스건병증) 특이 척도)', cat: '설문' },
    { id: 'cait', name: 'Cumberland 발목 불안정성 도구 (CAIT)', cat: '설문' },
  ],
  foot: [
    { id: 'f_arom', name: '발목·발가락 관절가동범위 (AROM/PROM)', cat: 'ROM' },
    { id: 'f_palpation', name: '발바닥·발꿈치뼈(종골) 촉진', cat: '촉진' },
    { id: 'windlass', name: 'Windlass 검사', cat: '특수검사' },
    { id: 'tinel_foot', name: '발목굴(족근관) Tinel 징후', cat: '신경학적' },
    { id: 'gastroc_length', name: '장딴지근·가자미근 길이 검사', cat: 'ROM' },
    { id: 'navicular_drop', name: '발배뼈(주상골) 하강 검사 (발 자세 평가)', cat: '시진' },
    { id: 'fpi', name: '발 자세 지수 (Foot Posture Index)', cat: '시진' },
    { id: 'bmi_check', name: '체질량지수(BMI) 측정', cat: '기본' },
    { id: 'heel_raise_f', name: '한발 뒤꿈치 들기 검사', cat: '기능' },
    { id: 'faam_f', name: '발·발목 기능척도 (FAAM) 설문', cat: '설문' },
  ],
};

function getExamsForRegion(region) {
  return [...EXAM_LIBRARY.common, ...(EXAM_LIBRARY[region] || [])];
}

function findExam(region, id) {
  return getExamsForRegion(region).find((e) => e.id === id);
}
