// 환자별 중재 처방 정답표 (Prescription answer key)
// ─────────────────────────────────────────────────────────────
// 키는 '환자id:중재id'. rx-library.js 의 RX.protos 에 정의된 원형을 골라
// 그 환자에게 맞는 정답 용량을 지정한다.
//
//   best : 정답 (배열이면 어느 것이든 정답)   → 1.0점
//   ok   : 허용 가능 (차선)                    → 0.5점
//   tip  : 결과 리포트에 보여 줄 근거 한 줄
//
// best 가 정의된 필드만 채점 대상이다. 여기에 없는 중재(대부분 비권고 중재)는
// 이름으로 원형을 추정해 같은 모양의 처방 화면을 띄우되 채점하지 않는다
// (비권고 중재를 고른 벌점은 ④ 치료계획에서 이미 반영된다).
//
// 표적 근육·분절 선택지는 환자의 region 으로 정해진다 (RX.pools 참고).

RX.plans = {

// ══════════════════════════════════════════════════════════════
// p1 김미영 — 가동성 결핍 동반 목통증 (아급성 3주, 자극성 중간)
// ══════════════════════════════════════════════════════════════
'p1:t1': { proto: 'joint_mob',
  best: { target: 'c45', grade: 'g3', position: 'end', dose: 'osc30', response: 'reassess', sched: 'w23_4' },
  ok: { grade: ['g4', 'g2'], position: ['mid'], dose: ['osc60'], sched: ['w12_8'] },
  tip: '분절 가동성 검사에서 저가동성이 확인된 C4-5·C5-6에 적용한다. 통증보다 가동범위 제한이 주 문제이므로 저항 구간까지 들어가는 Ⅲ등급이 적절하다.' },
'p1:t2': { proto: 'manipulation',
  best: { target: 'thoracic', screen: 'full', dose: 'x2', combine: 'with_ex', sched: 'w23_2' },
  ok: { dose: ['x1'] },
  tip: 'CPG는 급성기부터 등뼈 도수기법 병행을 권고한다. 시행 전 적신호·혈관·인대 선별을 마치고, 교정 직후 운동을 붙여야 효과가 유지된다.' },
'p1:t3': { proto: 'strength',
  best: { target: 'scap', mode: 'isotonic', load: 'l40', volume: 'v3x15', rest: 'r60', sched: 'w35', progress: 'rep_rule' },
  ok: { mode: ['closed_chain'], load: ['l60'], volume: ['v3x10'], sched: ['w23'], progress: ['pain_rule'] },
  tip: '어깨가슴·팔 강화는 목 운동 프로그램의 충실도를 높이기 위한 것이다. 무거운 부하보다 자세를 유지할 수 있는 중등도 부하·고반복이 맞다.' },
'p1:t4': { proto: 'endurance',
  best: { target: 'sh_girdle', load: 'l30', volume: 'hold', rest: 'r30', sched: 'w35_6' },
  ok: { target: ['scap', 'deep_ext'], load: ['bw'], volume: ['v2x20'], rest: ['r60'] },
  tip: '아급성 목통증의 핵심 중재. 목·어깨이음뼈 지구력은 저부하로 유지 시간을 늘려 가며 6주 이상 이어져야 한다.' },
'p1:t5': { proto: 'motor_control',
  best: { target: 'dnf', feedback: 'biofeedback', intensity: 'low', volume: 'h10x10', progress: 'to_function', sched: 'daily' },
  ok: { feedback: ['tactile'], volume: ['h5x10x3'], sched: ['w35'] },
  tip: 'CCFT에서 24 mmHg부터 목빗근 대상작용이 나타났다. 압력 바이오피드백으로 22 mmHg부터 10초 유지 10회씩, 대상작용 없이 되는 단계에서만 올린다.' },
'p1:t6': { proto: 'education',
  best: { content: 'ergonomic', frame: 'reassure_active', method: 'verbal_written', behavior: 'ergonomic', reinforce: 'each_visit' },
  ok: { content: ['stay_active', 'prognosis'], method: ['demo'], behavior: ['goal_setting'] },
  tip: 'CPG는 활동적 생활방식 증진과 인지·정서적 요인을 다루는 상담을 권고한다. 모니터 높이·휴식 주기 같은 구체적 작업환경 조정이 함께 가야 한다.' },

// ══════════════════════════════════════════════════════════════
// p2 박순자 — 유착관절주머니염 (동결기 이행, 자극성 높음)
// ══════════════════════════════════════════════════════════════
'p2:t1': { proto: 'education',
  best: { content: 'prognosis', frame: 'reassure_active', method: 'verbal_written', behavior: 'load_mgmt', reinforce: 'each_visit' },
  ok: { content: ['load_mgmt', 'stay_active'], method: ['demo'] },
  tip: 'CPG가 명시한 교육 3요소 — 자연 경과, 통증 없는 기능적 범위 내 활동 수정, 자극성에 맞춘 스트레칭 강도. "평생 못 쓰나요?"라는 불안을 예후 설명으로 다룬다.' },
'p2:t2': { proto: 'stretch',
  best: { target: 'post_cap', type: 'static', intensity: 'painfree', hold: 'h10', reps: 'r5', sched: 'tid' },
  ok: { type: ['pnf'], intensity: ['mild'], hold: ['h30'], reps: ['r3'], sched: ['daily'] },
  tip: '자극성이 높은 시기(야간통·안정 시 통증)에는 통증 없는 범위에서 짧게, 자주. 강도를 자극성에 맞추는 것이 이 CPG의 핵심 원칙이다.' },
'p2:t3': { proto: 'joint_mob',
  best: { target: ['gh_inf', 'gh_ant'], grade: 'g2', position: 'resting', dose: 'osc30', response: 'reassess', sched: 'w23_4' },
  ok: { target: ['gh_post'], grade: ['g1', 'g3'], position: ['mid'], dose: ['osc60'] },
  tip: '자극성이 높으므로 이완자세에서 통증 조절 목적의 Ⅰ·Ⅱ등급으로 시작한다. 제한 패턴(가쪽돌림>벌림>안쪽돌림)에 맞춰 아래쪽·앞쪽 활주를 우선한다.' },
'p2:t4': { proto: 'referral',
  best: { to: 'ortho', reason: 'injection', timing: 'concurrent', pt_plan: 'continue' },
  ok: { timing: ['now'] },
  tip: 'CPG 근거등급 A — 관절내 스테로이드 주사 + 가동술·스트레칭 병행이 도수치료 단독보다 단기(4~6주) 통증·기능에서 우수하다. 주사 후에도 물리치료를 이어가야 효과가 유지된다.' },
'p2:t5': { proto: 'swd',
  best: { mode: 'cont', applicator: 'inductive', dose: 'd2', time: 't15', sched: 'w23', combine: 'pre_stretch' },
  ok: { mode: ['pulsed'], applicator: ['capacitive'], dose: ['d3'], time: ['t20', 't10'] },
  tip: 'CPG는 물리적 인자를 "운동·스트레칭과 병행"할 때만 권고한다. 가열 직후 스트레칭·가동술로 이어가지 않으면 의미가 없다. 당뇨 환자이므로 감각 확인 후 낮은 용량에서 시작한다.' },
'p2:t6': { proto: 'hep',
  best: { count: 'c2_3', sched: 'bid', adherence: 'teachback', progress: 'criteria' },
  ok: { count: ['c5'], sched: ['daily'], adherence: ['log_review'] },
  tip: '가정 스트레칭은 치료실 중재의 필수 보완이다. 개수를 줄이고 치료실에서 직접 수행시켜 강도(통증 없는 범위)를 몸으로 익히게 한다.' },

// ══════════════════════════════════════════════════════════════
// p3 윤정심 — 손목터널증후군 경도~중등도 (만성 6개월)
// ══════════════════════════════════════════════════════════════
'p3:t1': { proto: 'orthosis',
  best: { device: 'neutral_splint', position: 'neutral', wear: 'night', period: 'p1_3m', combine: 'with_ex' },
  ok: { wear: ['day_task'], period: ['p2w'] },
  tip: 'CPG 권고등급 B — 야간 중립 자세(0~5° 폄) 손목 보조기. 폄 위치로 고정하면 손목굴 압력이 오히려 올라간다. 야간통으로 깨는 이 환자의 일차 중재.' },
'p3:t2': { proto: 'orthosis',
  best: { device: 'mcp_splint', position: 'neutral', wear: 'day_task', period: 'p1_3m', combine: 'with_ex' },
  ok: { device: ['neutral_splint'], wear: ['full'] },
  tip: '야간 착용만으로 부족하면 주간·증상 유발 활동 시로 확대하고, MCP 관절까지 포함하는 보조기를 고려한다 — CPG가 제시한 단계적 조정 전략.' },
'p3:t3': { proto: 'education',
  best: { content: 'load_mgmt', frame: 'reassure_active', method: 'verbal_written', behavior: 'load_mgmt', reinforce: 'each_visit' },
  ok: { content: ['self_monitor', 'ergonomic'], method: ['demo'] },
  tip: '손목 굽힘 유지 자세(전화기 들기·운전)가 증상을 만든다는 것을 이해시키고, 증상이 나올 때의 자가관리(손 털기 대신 자세 교정)를 교육한다.' },
'p3:t4': { proto: 'education',
  best: { content: 'ergonomic', frame: 'reassure_active', method: 'demo', behavior: 'ergonomic', reinforce: 'each_visit' },
  ok: { method: ['verbal_written'], behavior: ['load_mgmt'] },
  tip: '계산대 반복 작업이 위험요인이다. 스캔 동작 대체, 양손 교대 사용, 저타격력 키보드 등 구체적 대안을 직접 시연하고 재현시킨다.' },
'p3:t5': { proto: 'stretch',
  best: { target: 'flexor', type: 'static', intensity: 'painfree', hold: 'h30', reps: 'r5', sched: 'tid' },
  ok: { target: ['median_path', 'tcl'], type: ['dynamic'], intensity: ['mild'], hold: ['h10'], reps: ['r3'] },
  tip: '신경 증상이 있으므로 저림을 유발하지 않는 범위에서만. 보조기 단독보다 스트레칭을 결합한 프로그램이 낫다는 것이 CPG의 근거다.' },
'p3:t6': { proto: 'joint_mob',
  best: { target: 'carpal', grade: 'g3', position: 'mid', dose: 'osc30', response: 'reassess', sched: 'w23_4' },
  ok: { target: ['cervical', 'radiocarpal'], grade: ['g2'], position: ['resting'] },
  tip: 'CPG는 목뼈·팔을 포함한 도수치료를 단기 중재로 제시한다(권고등급 C). 손목뼈 활주로 손목굴 용적을 늘리는 것이 목표이며, 장기 단독 중재가 아니다.' },
'p3:t7': { proto: 'hotpack',
  best: { agent: 'hydro', layer: 'l6', time: 't15', timing: 'pre_ex', sched: 'w23' },
  ok: { agent: ['ir', 'fluido', 'warm_shower'], time: ['t10'], timing: ['standalone'], sched: ['daily'] },
  tip: '단기 증상 완화 보조로만 쓴다. 이 환자에게 온열 초음파는 CPG 비권고이므로 표재열 또는 투과열로 대체하는 것이 옳다.' },

// ══════════════════════════════════════════════════════════════
// p4 이재현 — 급성 허리통증 (가동성 결핍, 택배기사)
// ══════════════════════════════════════════════════════════════
'p4:t1': { proto: 'manipulation',
  best: { target: 'l45', screen: 'full', dose: 'x2', combine: 'with_ex', sched: 'w23_2' },
  ok: { target: ['tl', 'l13'], dose: ['x1'], sched: ['w12_6'] },
  tip: 'CPG 근거등급 A — 급성 허리통증에서 추력 도수교정. 반드시 적신호 선별 후 시행하고, 교정만으로 끝내지 말고 운동을 붙인다.' },
'p4:t2': { proto: 'mdt',
  best: { direction: 'extension', criteria: 'centralize', volume: 'r10', sched: 'q2h', monitor: 'peripheralize', posture: 'lordosis' },
  ok: { volume: ['r5'], sched: ['tid'] },
  tip: '방향선호는 진단명이 아니라 반복운동에 대한 증상 반응(중심화)으로 정한다. 말초화되면 즉시 중단하고 방향을 다시 찾는다.' },
'p4:t3': { proto: 'education',
  best: { content: 'stay_active', frame: 'reassure_active', method: 'verbal_written', behavior: 'goal_setting', reinforce: 'each_visit' },
  ok: { content: ['prognosis'], method: ['demo'], behavior: ['load_mgmt'] },
  tip: 'CPG는 척추의 구조적 안전성과 양호한 예후를 설명하고, 통증이 남아 있어도 조기에 활동·직장으로 복귀하도록 격려할 것을 권고한다.' },
'p4:t4': { proto: 'motor_control',
  best: { target: 'multifidus', feedback: 'tactile', intensity: 'low', volume: 'h10x10', progress: 'to_function', sched: 'daily' },
  ok: { target: ['tra'], feedback: ['biofeedback'], volume: ['h5x10x3'], sched: ['w35'] },
  tip: '급성기에는 분리 활성부터 시작해 자세 유지 → 사지 부하 → 실제 들기 동작으로 통합한다. 처음부터 고부하 몸통 운동으로 가지 않는다.' },
'p4:t5': { proto: 'gait_train',
  best: { task: 'lift', assist: 'independent', load: 'fwb', volume: 'v3x10', sched: 'w23' },
  ok: { task: ['bend'], volume: ['distance'], sched: ['w35'] },
  tip: '택배 상하차라는 실제 업무 동작을 그대로 훈련 과제로 삼는다. 단계적 복귀 계획(중량·횟수·시간)을 문서로 정해 주는 것이 CPG 권고다.' },
'p4:t6': { proto: 'aerobic',
  best: { mode: 'walk', intensity: 'i40', time: 't10', sched: 'w35' },
  ok: { mode: ['bike'], intensity: ['rpe'], time: ['t30'], sched: ['w5'] },
  tip: '급성기에는 저강도로 나눠서 시작한다. 유산소 활동 자체가 통증 회피 행동을 줄이는 능동적 대처의 일부다.' },
'p4:t13': { proto: 'hotpack',
  best: { agent: 'hydro', layer: 'l6', time: 't15', timing: 'pre_ex', sched: 'daily' },
  ok: { agent: ['warm_shower'], time: ['t10'], timing: ['standalone'], sched: ['prn'] },
  tip: '급성 허리통증의 표재열은 근거가 있으나, 어디까지나 운동·도수치료 앞에 붙는 자가관리 보조다. 이것만으로 프로그램을 구성하면 비권고가 된다.' },

// ══════════════════════════════════════════════════════════════
// p5 정우진 — 비관절염성 엉덩관절통 (FAI, 축구동호회)
// ══════════════════════════════════════════════════════════════
'p5:t1': { proto: 'education',
  best: { content: 'load_mgmt', frame: 'reassure_active', method: 'verbal_written', behavior: 'load_mgmt', reinforce: 'each_visit' },
  ok: { content: ['ergonomic', 'stay_active'], method: ['demo'], behavior: ['goal_setting'] },
  tip: '충돌을 만드는 자세(깊은 굽힘·양반다리)를 일시적으로 줄이는 것이지 활동을 끊는 것이 아니다. 어떤 동작을 얼마나 줄일지 구체적으로 정한다.' },
'p5:t2': { proto: 'strength',
  best: { target: 'abd', mode: 'closed_chain', load: 'l60', volume: 'v3x10', rest: 'r60', sched: 'w23', progress: 'pain_rule' },
  ok: { target: ['ext_rot', 'glute_max'], mode: ['isotonic'], load: ['l40'], volume: ['v3x15'], sched: ['w35'], progress: ['rep_rule'] },
  tip: '신체검사에서 확인된 결손(벌림근·가쪽돌림근 근력, 엉덩허리근 유연성)을 겨냥한다. 부하 증량은 운동 중·다음 날 통증을 기준으로 판단한다.' },
'p5:t3': { proto: 'motor_control',
  best: { target: 'trunk', feedback: 'mirror', intensity: 'low', volume: 'h5x10x3', progress: 'to_function', sched: 'daily' },
  ok: { target: ['abd'], feedback: ['tactile'], intensity: ['mid'], sched: ['w35'] },
  tip: '스쿼트·방향전환에서 골반이 무너지는 패턴을 시각 피드백으로 교정한다. 분리 훈련에 머무르지 말고 실제 축구 동작까지 이어져야 한다.' },
'p5:t4': { proto: 'joint_mob',
  best: { target: 'hip_post', grade: 'g3', position: 'end', dose: 'osc30', response: 'reassess', sched: 'w23_4' },
  ok: { target: ['hip_lat'], grade: ['g4', 'g2'], position: ['mid'] },
  tip: '관절주머니 제한이 의심되면 굽힘·안쪽돌림을 회복시키는 뒤쪽 활주를 쓴다. 근육·근막성 제한이면 연부조직 가동술로 갈아탄다 — 소견에 따라 기법을 고른다.' },
'p5:t5': { proto: 'gait_train',
  best: { task: 'cut', assist: 'independent', load: 'fwb', volume: 'distance', sched: 'w23' },
  ok: { task: ['single_leg', 'squat'], volume: ['v10min', 'v3x10'], sched: ['w35'] },
  tip: '직선 달리기 → 방향전환 → 슈팅 순으로 부하를 올린다. 단계마다 통증·다음 날 반응을 확인하고 통과 기준을 정해 두는 것이 재발을 막는다.' },

// ══════════════════════════════════════════════════════════════
// p6 최영숙 — 엉덩관절 골관절염 (68F, 과체중)
// ══════════════════════════════════════════════════════════════
'p6:t1': { proto: 'education',
  best: { content: 'exercise_why', frame: 'reassure_active', method: 'verbal_written', behavior: 'goal_setting', reinforce: 'each_visit' },
  ok: { content: ['load_mgmt', 'stay_active'], method: ['demo'], behavior: ['load_mgmt'] },
  tip: 'CPG 근거등급 A. 관절염은 "닳는 병이니 아끼라"가 아니라 "운동이 통증과 기능을 개선한다"는 틀로 설명해야 운동 순응이 생긴다.' },
'p6:t2': { proto: 'strength',
  best: { target: 'abd', mode: 'isotonic', load: 'l60', volume: 'v3x10', rest: 'r60', sched: 'w15', progress: 'rep_rule' },
  ok: { target: ['glute_max', 'quad_ham'], mode: ['closed_chain'], load: ['l40'], volume: ['v3x15'], sched: ['w23', 'w35'], progress: ['pain_rule'] },
  tip: 'CPG 명시 용량 — 6~12주간 주 1~5회의 개별화된 유연성·근력·지구력 운동. 벌림근과 폄근이 중심이다.' },
'p6:t3': { proto: 'joint_mob',
  best: { target: 'hip_lat', grade: 'g3', position: 'end', dose: 'osc30', response: 'reassess', sched: 'w13_612' },
  ok: { target: ['hip_post', 'hip_ant'], grade: ['g4', 'g2'], position: ['mid'], dose: ['osc60'] },
  tip: 'CPG 명시 용량 — 6~12주간 주 1~3회의 추력/비추력 가동술 + 연부조직 가동술. 안쪽돌림 15° 미만·굽힘 115° 이하의 제한을 표적으로 삼는다.' },
'p6:t4': { proto: 'gait_train',
  best: { task: 'walk', assist: 'aid', load: 'fwb', volume: 'v10min', sched: 'w23' },
  ok: { task: ['single_leg', 'squat'], assist: ['independent'], volume: ['v3x10'], sched: ['w35'] },
  tip: '지팡이는 아픈 다리의 반대쪽 손으로 짚는다. 낙상 위험 평가 결과에 맞춰 균형 훈련과 함께 처방하는 것이 CPG 권고다.' },
'p6:t5': { proto: 'aerobic',
  best: { mode: 'bike', intensity: 'i40', time: 't30', sched: 'w35' },
  ok: { mode: ['aqua', 'walk'], intensity: ['rpe', 'i60'], time: ['t10'], sched: ['w5'] },
  tip: '고정식 자전거·수중운동처럼 관절 충격이 적은 방식을 고른다. 체중 감량과 심폐 기능 개선이 동시에 목표다.' },
'p6:t6': { proto: 'ultrasound',
  best: { freq: 'f1', duty: 'cont', intensity: 'i10', time: 't5', coupling: 'gel', sched: 'x10_2w' },
  ok: { time: ['t8', 't10'], intensity: ['i15'] },
  tip: 'CPG가 용량까지 명시한 드문 예 — 1 MHz · 1 W/cm² · 2주간 총 10회. 핫팩·운동과 함께 쓸 때만 권고되며, 단독 프로그램은 비권고다.' },
'p6:t7': { proto: 'referral',
  best: { to: 'nutrition', reason: 'comorbid', timing: 'concurrent', pt_plan: 'continue' },
  ok: { to: ['internal'], reason: ['nonresponse'] },
  tip: '체중은 엉덩관절 부하를 직접 좌우한다. 물리치료를 멈추지 않고 의사·영양사와 병행하는 것이 원칙이다.' },

// ══════════════════════════════════════════════════════════════
// p7 강대호 — 안쪽 반달연골 손상 (52M, 등산애호가)
// ══════════════════════════════════════════════════════════════
'p7:t1': { proto: 'rom_ex',
  best: { target: 'tf_ext', assist: 'active', range: 'to_onset', volume: 'v10x3', sched: 'tid' },
  ok: { target: ['tf_flex'], assist: ['aarom'], range: ['painfree'], volume: ['hold'], sched: ['daily'] },
  tip: '완전 폄 회복이 먼저다. 폄 결손이 남으면 보행 패턴과 넙다리네갈래근 활성이 함께 무너진다. 조기에, 자주, 통증이 막 시작되는 지점까지.' },
'p7:t2': { proto: 'strength',
  best: { target: 'quad', mode: 'closed_chain', load: 'l60', volume: 'v3x10', rest: 'r60', sched: 'w35', progress: 'pain_rule' },
  ok: { target: ['ham', 'hip_post'], mode: ['isotonic', 'isometric'], load: ['l40', 'l80'], volume: ['v3x15'], sched: ['w23'], progress: ['rep_rule'] },
  tip: '반달연골 부하를 줄이려면 깊은 굽힘 없는 닫힌사슬(0~60°)에서 시작한다. 넙다리뒤근육을 함께 키워 정강뼈 앞쪽 전단을 억제한다.' },
'p7:t3': { proto: 'nmes',
  best: { target: 'quad', wave: 'sym_bi', freq: 'f50', pw: 'p400', duty: 'd1_5', amp: 'max_tol', reps: 'r10', posture: 'isometric', sched: 'w35' },
  ok: { wave: ['russian'], freq: ['f35'], pw: ['p250', 'p600'], duty: ['d1_3'], amp: ['visible'], reps: ['r15'], posture: ['functional'], sched: ['w23'] },
  tip: 'NMES는 강도가 곧 효과다. "참을 수 있는 최대"까지 올려야 자발적 수축을 넘어서는 이득이 생기고, 피로를 막기 위해 1:5 정도의 휴식비를 준다.' },
'p7:t4': { proto: 'hep',
  best: { count: 'c2_3', sched: 'daily', adherence: 'teachback', progress: 'criteria' },
  ok: { count: ['c5'], sched: ['bid', 'w35'], adherence: ['log_review'] },
  tip: 'CPG는 감독 하 재활과 홈 프로그램의 병행, 그리고 환자가 스스로 진행할 수 있게 만드는 교육을 함께 권고한다.' },
'p7:t5': { proto: 'gait_train',
  best: { task: 'hike', assist: 'independent', load: 'fwb', volume: 'distance', sched: 'w35' },
  ok: { task: ['gait', 'squat'], load: ['pwb'], volume: ['v10min'], sched: ['w23'] },
  tip: '평지 걷기 → 경사 → 등산 순으로 올린다. 거리·시간을 주당 10 % 정도씩 늘리고 다음 날 부종·통증으로 확인한다.' },

// ══════════════════════════════════════════════════════════════
// p8 한지수 — 앞십자인대 삠 (22F, 축구선수)
// ══════════════════════════════════════════════════════════════
'p8:t1': { proto: 'rom_ex',
  best: { target: 'tf_ext', assist: 'aarom', range: 'to_onset', volume: 'hold', sched: 'tid' },
  ok: { target: ['tf_flex', 'patella'], assist: ['passive', 'active'], range: ['painfree'], volume: ['v10x3'], sched: ['daily'] },
  tip: 'CPG는 부종 조절과 즉각적(조기) 가동을 함께 요구한다. 완전 폄 회복이 최우선이며, 폄 결손은 나중에 되돌리기 훨씬 어렵다.' },
'p8:t2': { proto: 'strength',
  best: { target: 'quad', mode: 'isotonic', load: 'l80', volume: 'v3x10', rest: 'r180', sched: 'w23', progress: 'pain_rule' },
  ok: { target: ['ham'], mode: ['closed_chain', 'eccentric', 'open_chain'], load: ['l60'], volume: ['v3x6'], rest: ['r60'], sched: ['w35'], progress: ['rep_rule'] },
  tip: 'CPG 근거등급 A — 체중부하와 비체중부하 운동을 "병행"하고 구심성·원심성을 모두 넣는다. 열린사슬을 무조건 금지하는 것은 근거에 맞지 않는다.' },
'p8:t3': { proto: 'nmes',
  best: { target: 'quad', wave: 'sym_bi', freq: 'f50', pw: 'p400', duty: 'd1_5', amp: 'max_tol', reps: 'r10', posture: 'isometric', sched: 'w35' },
  ok: { wave: ['russian'], freq: ['f35'], pw: ['p250'], duty: ['d1_3'], amp: ['visible'], reps: ['r15'], posture: ['functional'], sched: ['w23'] },
  tip: 'CPG는 6~8주간 근력운동과 병행하는 NMES를 권고한다. 근력운동을 대체하는 것이 아니라 넙다리네갈래근 활성 억제를 푸는 보조다.' },
'p8:t4': { proto: 'balance',
  best: { base: 'single_foam', vision: 'eyes_open', task: 'perturb', volume: 'v30x3', sched: 'w35_6' },
  ok: { base: ['single_firm', 'dynamic'], vision: ['head_move', 'eyes_closed'], task: ['reach', 'sport'], volume: ['v10min'], sched: ['daily_4w'] },
  tip: '비수술 후보 선별(Fitzgerald 기준)에 해당하면 perturbation 훈련이 핵심이 된다. 지지면·시각·과제 중 한 번에 하나씩만 어렵게 한다.' },
'p8:t5': { proto: 'cryo',
  best: { agent: 'cryo_cuff', time: 't15', combine: 'compress_elev', sched: 'q2h' },
  ok: { agent: ['icepack'], time: ['t10'], combine: ['motion'], sched: ['tid', 'post_ex'] },
  tip: '급성기 통증·부종 관리용 보조다. 압박·거상과 함께 쓰고, 냉각 때문에 조기 가동을 미루지 않는다.' },
'p8:t6': { proto: 'referral',
  best: { to: 'ortho', reason: 'decision', timing: 'concurrent', pt_plan: 'continue' },
  ok: { to: ['surgeon'], reason: ['nonresponse', 'imaging'], timing: ['now'] },
  tip: '수술 여부는 공동 의사결정 사안이다. ACL-RSI로 확인된 복귀 심리 요인도 함께 다뤄야 하며, 상담 중에도 재활은 계속된다.' },
'p8:t7': { proto: 'orthosis',
  best: { device: 'functional_acl', position: 'functional', wear: 'day_task', period: 'p1_3m', combine: 'with_ex' },
  ok: { device: ['hinged'], wear: ['full'], period: ['p2w'] },
  tip: 'CPG는 기능성 보조기의 효과를 강하게 지지하지 않는다 — 환자 선호를 반영해 결정하되, 운동 프로그램을 대체하지 않는다는 조건이 붙는다.' },
'p8:t11': { proto: 'balance',
  best: { base: 'single_foam', vision: 'eyes_open', task: 'perturb', volume: 'v30x3', sched: 'w35_6' },
  ok: { base: ['dynamic', 'single_firm'], vision: ['head_move'], task: ['sport'], volume: ['v10min'], sched: ['daily_4w'] },
  tip: 'Fitzgerald 선별(무릎이 꺾이는 일 1회 이하·한발뛰기 80 % 이상·근력 80 % 이상·일상 기능 양호)을 통과하면 perturbation 중심 재활로 간다.' },
'p8:t12': { proto: 'plyometric',
  best: { stage: 'multiplanar', cue: 'quality_feedback', volume: 'v3x8', rest: 'r120', sched: 'w23_6', criteria: 'lsi90' },
  ok: { stage: ['unilateral', 'sport'], volume: ['contacts'], rest: ['r60'], criteria: [] },
  tip: 'ACL 예방 CPG의 핵심 — 착지 정렬을 실시간으로 교정하는 질적 지도가 있어야 효과가 난다. 횟수만 채우는 프로그램은 재부상을 줄이지 못한다. 시즌 중에도 주 2~3회 유지해야 한다.' },

// ══════════════════════════════════════════════════════════════
// p9 문가영 — 무릎넙다리 통증 증후군 (24F, 러닝 초보)
// ══════════════════════════════════════════════════════════════
'p9:t1': { proto: 'strength',
  best: { target: 'hip_post', mode: 'closed_chain', load: 'l60', volume: 'v3x10', rest: 'r60', sched: 'w35', progress: 'rep_rule' },
  ok: { target: ['quad'], mode: ['isotonic', 'open_chain'], load: ['l40', 'l80'], volume: ['v3x15'], sched: ['w23'], progress: ['pain_rule'] },
  tip: 'CPG 근거등급 A — 엉덩관절과 무릎을 함께 겨냥하되 초기에는 뒤가쪽 엉덩관절 근육을 우선한다. 체중부하 스쿼트와 비체중부하 폄 운동을 병행한다.' },
'p9:t2': { proto: 'hep',
  best: { count: 'c2_3', sched: 'daily', adherence: 'teachback', progress: 'criteria' },
  ok: { count: ['c5'], sched: ['w35', 'bid'], adherence: ['log_review'] },
  tip: 'CPG가 가장 강하게 권고하는 것은 "결합 중재" — 운동치료를 중심에 두고 발보조기·테이핑·무릎뼈가동술·스트레칭을 붙인다. 순응도가 결과를 좌우한다.' },
'p9:t3': { proto: 'orthosis',
  best: { device: 'prefab_orthosis', position: 'neutral', wear: 'day_task', period: 'p2w', combine: 'with_ex' },
  ok: { device: ['custom_orthosis'], wear: ['full'], period: ['p1_3m'] },
  tip: 'CPG는 과다엎침 환자에게 기성 발보조기를 최대 6주의 단기로, 운동과 결합해서 쓰라고 명시한다. 맞춤 보조기가 기성보다 낫다는 근거는 없다.' },
'p9:t4': { proto: 'taping',
  best: { purpose: 'realign', tape: 'mcconnell', tension: 't50', check: 'symptom_test', duration: 'd1' },
  ok: { purpose: ['facilitate'], tape: ['rigid'], tension: ['t25'], duration: ['d3'] },
  tip: '테이핑은 즉각적 통증 감소를 위한 초기 4주의 보조다. 붙인 뒤 유발 동작을 다시 시켜 통증이 실제로 줄었는지 확인해야 "맞춤형"이 된다.' },
'p9:t5': { proto: 'gait_train',
  best: { task: 'run', assist: 'independent', load: 'fwb', volume: 'distance', sched: 'w23' },
  ok: { task: ['land', 'squat'], volume: ['v10min'], sched: ['w35'] },
  tip: 'CPG는 러닝 게이트 재교육을 복수 세션에 걸쳐 시행할 것을 권고한다 — 앞발 착지 큐잉, 케이던스 증가, 러닝 중 엉덩관절 모음 감소.' },
'p9:t6': { proto: 'education',
  best: { content: 'load_mgmt', frame: 'reassure_active', method: 'verbal_written', behavior: 'load_mgmt', reinforce: 'each_visit' },
  ok: { content: ['exercise_why', 'prognosis'], method: ['demo'], behavior: ['goal_setting'] },
  tip: '러닝량 급증이 원인이다. 부하 관리와 함께 운동공포(kinesiophobia)를 다루고, 운동치료 순응이 왜 중요한지 이해시킨다.' },

// ══════════════════════════════════════════════════════════════
// p10 오민석 — 발꿈치힘줄병증 중간부 (35M, 마라토너)
// ══════════════════════════════════════════════════════════════
'p10:t1': { proto: 'eccentric',
  best: { target: 'achilles', protocol: 'alfredson', volume: 'v3x15', tempo: 'slow3', load_rule: 'painful_ok', sched: 'bid_12w', load_mgmt: 'modify' },
  ok: { protocol: ['hsr', 'silbernagel'], tempo: ['slow6'], load_rule: ['nrs5'], sched: ['w3_12w'] },
  tip: 'CPG 근거등급 A. Alfredson 프로토콜 — 무릎 편 자세와 굽힌 자세 두 가지 heel drop을 15회 3세트씩, 하루 2회, 12주. 통증이 있어도 견딜 만하면 배낭으로 무게를 더한다.' },
'p10:t2': { proto: 'education',
  best: { content: 'load_mgmt', frame: 'reassure_active', method: 'verbal_written', behavior: 'load_mgmt', reinforce: 'each_visit' },
  ok: { content: ['prognosis', 'exercise_why'], method: ['demo'], behavior: ['goal_setting'] },
  tip: '훈련량과 언덕 훈련을 조절하되 완전 휴식은 아니다. 통증 모니터링(운동 중 NRS 5 이하, 다음 날 아침 뻣뻣함 악화 없음)을 기준으로 점진 증량한다.' },
'p10:t3': { proto: 'laser',
  best: { wave: 'w830', dose: 'd4', contact: 'point', time: 't5', sched: 'w23' },
  ok: { wave: ['w904', 'w650'], dose: ['d1', 'd10'], contact: ['scan'], time: ['t3', 't10'], sched: ['w35'] },
  tip: 'CPG 권고등급 B — 저출력 레이저는 원심성 운동의 보조로 통증 감소에 쓴다. 단독 중재가 아니라 운동 프로그램에 얹는 것이다.' },
'p10:t4': { proto: 'iontophoresis',
  best: { drug: 'dexa', current: 'c2', dose: 'd40', sched: 'w23' },
  ok: { current: ['c4'], dose: ['d20', 'd80'], sched: ['w1'] },
  tip: 'CPG 권고등급 B — 덱사메타손 이온도입이 급성기 통증 감소에 도움이 된다. 이 역시 원심성 운동을 대체하지 않는다.' },
'p10:t5': { proto: 'stretch',
  best: { target: 'triceps', type: 'static', intensity: 'mild', hold: 'h30', reps: 'r3', sched: 'daily' },
  ok: { type: ['pnf'], intensity: ['end_range'], hold: ['h60'], reps: ['r5'], sched: ['tid', 'w35'] },
  tip: '발등굽힘 제한이 있을 때 보조적으로 쓴다. 스트레칭 단독은 원심성 부하 프로그램보다 열등하다는 것이 CPG의 결론이다.' },
'p10:t6': { proto: 'stm',
  best: { target: 'achilles', technique: 'deep_stroke', pressure: 'p_mid', dose: 'd3', after: 'stretch_ex', sched: 'w12' },
  ok: { target: ['triceps'], technique: ['cross_fiber', 'iastm'], pressure: ['p_light'], dose: ['d60'], sched: ['w23'] },
  tip: '연부조직 가동술은 힘줄 부담을 잠시 덜어 주는 보조다. 시행 후 반드시 운동으로 이어 새 상태를 정착시킨다.' },
'p10:t7': { proto: 'orthosis',
  best: { device: 'custom_orthosis', position: 'neutral', wear: 'day_task', period: 'p1_3m', combine: 'with_ex' },
  ok: { device: ['prefab_orthosis', 'heel_lift'], wear: ['full'], period: ['p2w'] },
  tip: 'CPG 권고등급 C — 러닝 시 통증 감소와 발 운동학 교정 목적. 뒤꿈치 올림 패드만 단독으로 쓰는 것은 근거가 더 약하다.' },

// ══════════════════════════════════════════════════════════════
// p11 임태양 — 가쪽 발목삠 2도 (19M, 급성/보호 단계)
// ══════════════════════════════════════════════════════════════
'p11:t1': { proto: 'orthosis',
  best: { device: 'lace_brace', position: 'neutral', wear: 'day_task', period: 'p2w', combine: 'with_ex' },
  ok: { device: ['semi_rigid', 'tape'], wear: ['full'], period: ['p1_3m'] },
  tip: 'CPG 근거등급 A — 급성기 외부 지지 + 통증 허용 범위의 점진적 체중부하. 고정이 아니라 "보호하면서 움직이게 하는" 장치다.' },
'p11:t2': { proto: 'joint_mob',
  best: { target: 'talus_ant', grade: 'g2', position: 'resting', dose: 'osc30', response: 'pain_limit', sched: 'w23_4' },
  ok: { target: ['talus_post', 'fibula'], grade: ['g1', 'g3'], position: ['mid'], response: ['reassess'] },
  tip: 'CPG 근거등급 A — 급성기에는 통증이 없는 범위의 연부조직·관절 가동술과 앞→뒤 목말뼈 가동술. 자극성이 높으므로 이완자세에서 낮은 등급으로 시작한다.' },
'p11:t3': { proto: 'cryo',
  best: { agent: 'icepack', time: 't15', combine: 'compress_elev', sched: 'q2h' },
  ok: { agent: ['cryo_cuff', 'immersion'], time: ['t10'], combine: ['motion'], sched: ['tid'] },
  tip: 'CPG 권고등급 B — 간헐적 냉치료 반복과 압박·거상 교육. 수상 초기 48~72시간 동안 2시간 간격이 표준이다.' },
'p11:t4': { proto: 'strength',
  best: { target: 'peroneal', mode: 'isotonic', load: 'l40', volume: 'v3x15', rest: 'r60', sched: 'w35', progress: 'pain_rule' },
  ok: { target: ['tib_ant', 'triceps'], mode: ['closed_chain', 'isometric'], load: ['bw', 'l60'], volume: ['v3x10'], sched: ['daily', 'w23'], progress: ['rep_rule'] },
  tip: 'CPG 근거등급 A — ROM → 근력(특히 가쪽번짐근) → 체중부하 기능운동 순서. 종아리근은 다시 삐는 것을 막는 일차 방어선이다.' },
'p11:t5': { proto: 'balance',
  best: { base: 'single_foam', vision: 'eyes_open', task: 'static', volume: 'v30x3', sched: 'daily_4w' },
  ok: { base: ['single_firm', 'dynamic'], vision: ['eyes_closed'], task: ['reach', 'perturb'], volume: ['v10min'], sched: ['w35_6'] },
  tip: 'CPG 근거등급 A — 불안정 지지면 한발 균형 훈련. 급성 발목삠 후 감각운동 훈련은 재발률을 낮추는 가장 확실한 중재다.' },
'p11:t6': { proto: 'plyometric',
  best: { stage: 'multiplanar', cue: 'quality_feedback', volume: 'v3x8', rest: 'r120', sched: 'w23_6', criteria: 'lsi90' },
  ok: { stage: ['bilateral', 'unilateral', 'sport'], volume: ['contacts'], rest: ['r60'], criteria: [] },
  tip: '복귀 단계 — 균형 훈련에 농구 관련 동작(점프 착지·컷팅)을 얹고, 정해 둔 기준을 충족한 뒤에 대회로 돌아간다. 통증만으로 판단하지 않는다.' },
'p11:t7': { proto: 'swd',
  best: { mode: 'pulsed', applicator: 'capacitive', dose: 'd1', time: 't15', sched: 'w23', combine: 'pre_stretch' },
  ok: { applicator: ['inductive'], dose: ['d2'], time: ['t10', 't20'], sched: ['w35'] },
  tip: 'CPG 권고등급 C — 부종·보행 결함 감소 목적의 박동성(펄스) 단파투과열. 부종이 남은 급성기이므로 온열이 생기는 연속 모드는 쓰지 않는다.' },

// ══════════════════════════════════════════════════════════════
// p12 서혜란 — 발바닥근막염 (48F, 교사)
// ══════════════════════════════════════════════════════════════
'p12:t1': { proto: 'stretch',
  best: { target: 'plantar', type: 'static', intensity: 'mild', hold: 'h30', reps: 'r3', sched: 'tid' },
  ok: { target: ['triceps', 'achilles'], type: ['pnf'], intensity: ['end_range'], hold: ['h60', 'h10'], reps: ['r5'], sched: ['daily'] },
  tip: 'CPG 근거등급 A. 발가락을 발등쪽으로 젖혀 근막을 감는 특이적 스트레칭이 장딴지 스트레칭보다 낫고, 첫 발을 딛기 전 침대에서 하는 것이 효과적이다. 힐 패드를 함께 쓰면 효과가 커진다.' },
'p12:t2': { proto: 'joint_mob',
  best: { target: 'talocrural', grade: 'g3', position: 'end', dose: 'osc30', response: 'reassess', sched: 'w23_4' },
  ok: { target: ['subtalar', 'mtp1', 'midfoot'], grade: ['g4', 'g2'], position: ['mid'], dose: ['osc60'] },
  tip: 'CPG 근거등급 A — 발등굽힘 가동성과 장딴지 유연성 회복이 목표다. 발등굽힘 제한은 발바닥근막염의 가장 강력한 위험요인이다.' },
'p12:t3': { proto: 'taping',
  best: { purpose: 'realign', tape: 'rigid', tension: 't50', check: 'symptom_test', duration: 'd3' },
  ok: { purpose: ['support'], tape: ['kinesio', 'mcconnell'], tension: ['t25'], duration: ['d1'] },
  tip: 'CPG 근거등급 A — 엎침 방지(antipronation) 테이핑. 즉각적 통증 감소를 확인하고 유지하며, 탄력 테이프를 덧붙일 수 있다.' },
'p12:t4': { proto: 'orthosis',
  best: { device: 'prefab_orthosis', position: 'neutral', wear: 'full', period: 'p1_3m', combine: 'with_ex' },
  ok: { device: ['custom_orthosis', 'heel_pad'], wear: ['day_task'], period: ['p2w'] },
  tip: 'CPG 근거등급 A — 충격 완화와 안쪽 세로아치 지지. 기성과 맞춤 사이에 효과 차이가 확인되지 않았으므로 기성부터 시도해도 된다.' },
'p12:t5': { proto: 'orthosis',
  best: { device: 'night_splint', position: 'neutral', wear: 'night', period: 'p1_3m', combine: 'with_ex' },
  ok: { position: ['functional'], period: ['p2w'] },
  tip: 'CPG 근거등급 A — 1~3개월 야간 부목. 아침 첫 발 통증이 뚜렷한 환자에게 특히 유효하다. (같은 야간 부목이 발꿈치힘줄병증에서는 비권고인 점과 대조된다.)' },
'p12:t6': { proto: 'education',
  best: { content: 'ergonomic', frame: 'reassure_active', method: 'verbal_written', behavior: 'ergonomic', reinforce: 'each_visit' },
  ok: { content: ['load_mgmt'], method: ['demo'], behavior: ['load_mgmt'] },
  tip: 'CPG 권고등급 C — 로커바텀 신발과 보조기의 결합, 근무 중 신발 교대 착용. 하루 종일 서서 일하는 직업 조건을 바꾸는 것이 중재의 일부다.' },
'p12:t7': { proto: 'referral',
  best: { to: 'nutrition', reason: 'comorbid', timing: 'concurrent', pt_plan: 'continue' },
  ok: { to: ['internal'], reason: ['nonresponse'] },
  tip: 'BMI 상승은 CPG가 명시한 위험요인이다. 체중 감량 교육과 영양 협진을 병행하되 물리치료를 미루지 않는다.' },
'p12:t8': { proto: 'strength',
  best: { target: 'intrinsic', mode: 'isotonic', load: 'bw', volume: 'v3x15', rest: 'r30', sched: 'daily', progress: 'rep_rule' },
  ok: { target: ['tib_post', 'hip_prox'], mode: ['closed_chain', 'isometric'], load: ['l40'], volume: ['v3x10', 'iso10'], rest: ['r60'], sched: ['w35'], progress: ['pain_rule'] },
  tip: '엎침 조절 근육(발 내재근·뒤정강근)의 신경근 재교육. 체중 부하 조건에서 아치를 능동으로 만드는 훈련이 핵심이며 무거운 부하는 필요 없다.' },
'p12:t9': { proto: 'iontophoresis',
  best: { drug: 'dexa', current: 'c2', dose: 'd40', sched: 'w23' },
  ok: { drug: ['acetic'], current: ['c4'], dose: ['d20', 'd80'], sched: ['w1'] },
  tip: 'CPG 권고등급 C — 2~4주의 단기 보조. 스트레칭·도수치료·보조기라는 근간을 갖춘 뒤에 얹는 것이지, 이것으로 프로그램을 구성하면 안 된다.' },

// ══════════════════════════════════════════════════════════════
// p13 배수경 — 두통 동반 목통증 (목인성 두통)
// ══════════════════════════════════════════════════════════════
'p13:t1': { proto: 'mwm',
  best: { target: 'c0_2', criteria: 'painfree', dose: 'r3x6', overpressure: 'yes', home: 'belt', sched: 'daily' },
  ok: { target: ['c45'], dose: ['r3x10', 'r1x3'], home: ['clinic'], sched: ['w23'] },
  tip: 'CPG 권고등급 B — C1-2 self-SNAG. 방향은 "통증 없이 두통이 즉시 줄어드는" 쪽으로 정하고(PILL 원칙), 벨트를 이용한 자가 시행을 매일 하도록 교육한다.' },
'p13:t2': { proto: 'joint_mob',
  best: { target: 'c0_2', grade: 'g3', position: 'end', dose: 'osc30', response: 'reassess', sched: 'w23_4' },
  ok: { target: ['c45'], grade: ['g4', 'g2'], position: ['mid'], dose: ['osc60'] },
  tip: 'CFRT 양성이 가리키는 C1-2를 포함한 위목뼈(C0-1~C2-3)가 표적이다. 목인성 두통은 위목뼈 분절 기능장애에서 나온다.' },
'p13:t3': { proto: 'manipulation',
  best: { target: 'thoracic', screen: 'full', dose: 'x2', combine: 'with_ex', sched: 'w23_2' },
  ok: { dose: ['x1'], sched: ['w12_6'] },
  tip: '등뼈 병행은 권고등급 C로 목뼈 중재만큼 강하지는 않다. 그래도 시행 전 선별과 시행 후 운동 병행 원칙은 동일하다.' },
'p13:t4': { proto: 'motor_control',
  best: { target: 'dnf', feedback: 'biofeedback', intensity: 'low', volume: 'h10x10', progress: 'to_function', sched: 'daily' },
  ok: { target: ['scap', 'deep_ext'], feedback: ['tactile'], volume: ['h5x10x3'], sched: ['w35'] },
  tip: 'CPG 권고등급 B — 목·어깨이음뼈 근력·지구력 운동에 깊은목굽힘근 협응 훈련을 포함한다. 목인성 두통에서 가장 재발을 잘 막는 축이다.' },
'p13:t5': { proto: 'education',
  best: { content: 'ergonomic', frame: 'reassure_active', method: 'demo', behavior: 'ergonomic', reinforce: 'each_visit' },
  ok: { content: ['stay_active', 'load_mgmt'], method: ['verbal_written'], behavior: ['load_mgmt'] },
  tip: '판서·채점 자세가 증상을 만든다. 화이트보드 높이와 휴식 주기를 구체적 숫자로 정하고 직접 시연시켜 확인한다.' },
'p13:t6': { proto: 'education',
  best: { content: 'self_monitor', frame: 'reassure_active', method: 'verbal_written', behavior: 'goal_setting', reinforce: 'each_visit' },
  ok: { content: ['prognosis', 'exercise_why'], method: ['demo'] },
  tip: '두통 일지와 HIT-6 재평가로 중재 반응을 추적한다. 목인성 두통은 주관 증상이 주된 지표이므로 기록이 곧 평가다.' },

// ══════════════════════════════════════════════════════════════
// p14 노경택 — 방사통 동반 목통증 (목뼈 신경뿌리병증)
// ══════════════════════════════════════════════════════════════
'p14:t1': { proto: 'traction',
  best: { region: 'cerv_sup', mode: 'intermittent', force: 'f12', time: 't15', combine: 'with_ex', sched: 'w23' },
  ok: { region: ['cerv_sit'], mode: ['static'], force: ['f7'], time: ['t10', 't20'], sched: ['w35'] },
  tip: 'CPG 권고등급 B — 견인은 "만성 방사통 동반" 목통증에서 도수치료·운동과 결합할 때만 권고된다. 굽힘 15~25°에서 체중의 10~15 %, 간헐 방식이 표준이다. (같은 견인이 가동성 결핍 범주에서는 부적합인 점과 대조된다.)' },
'p14:t2': { proto: 'neural_mob',
  best: { target: 'median', technique: 'slider', range: 'symptom_free', dose: 'r10x3', sched: 'daily_home' },
  ok: { target: ['ulnar', 'radial'], technique: ['prox_first', 'tensioner'], range: ['onset'], dose: ['r30'], sched: ['w23'] },
  tip: '신경 자극이 목표가 아니라 활주 회복이 목표다. 자극성이 있는 시기에는 증상이 나기 직전까지의 슬라이더로 시작하고, 반응이 좋아지면 긴장 기법으로 넘어간다.' },
'p14:t3': { proto: 'joint_mob',
  best: { target: 'cerv_lat', grade: 'g3', position: 'mid', dose: 'osc30', response: 'reassess', sched: 'w23_4' },
  ok: { target: ['c45', 'thoracic', 'c67'], grade: ['g2', 'g4'], position: ['resting', 'end'] },
  tip: '신경뿌리 압박을 줄이는 가쪽 활주 방향을 우선한다. 신경학적 증상이 늘어나면 즉시 등급을 낮춘다 — 재평가가 곧 안전장치다.' },
'p14:t4': { proto: 'strength',
  best: { target: 'scap', mode: 'isotonic', load: 'l40', volume: 'v3x15', rest: 'r60', sched: 'w35', progress: 'pain_rule' },
  ok: { target: ['sh_girdle', 'deep_ext'], mode: ['closed_chain'], load: ['l60', 'bw'], volume: ['v3x10'], sched: ['w23'], progress: ['rep_rule'] },
  tip: '어깨가슴 안정화를 포함한 목·어깨이음뼈 근력·지구력 운동. 신경 증상이 있으므로 증상 반응을 기준으로 부하를 올린다.' },
'p14:t5': { proto: 'education',
  best: { content: 'prognosis', frame: 'reassure_active', method: 'verbal_written', behavior: 'load_mgmt', reinforce: 'each_visit' },
  ok: { content: ['stay_active', 'self_monitor'], method: ['demo'], behavior: ['goal_setting', 'ergonomic'] },
  tip: '목뼈 신경뿌리병증은 대부분 보존치료로 좋아진다는 예후 설명이 핵심이다. 팔을 머리 위로 올리면 편해지는 자세(어깨벌림 완화 징후)를 활용하도록 알려 주고, 흡연은 회복을 늦추므로 금연 상담을 붙인다.' },
'p14:t6': { proto: 'gait_train',
  best: { task: 'carry', assist: 'independent', load: 'fwb', volume: 'distance', sched: 'w23' },
  ok: { task: ['driving', 'desk'], volume: ['v3x10', 'v10min'], sched: ['w35'] },
  tip: '운전 중 자세 변경 주기, 상하차 시 팔 높이 조절처럼 실제 업무 동작을 바꾼다. 단계적 복귀 일정을 함께 정한다.' },
'p14:t7': { proto: 'education',
  best: { content: 'self_monitor', frame: 'reassure_active', method: 'verbal_written', behavior: 'goal_setting', reinforce: 'each_visit' },
  ok: { content: ['prognosis'], method: ['demo'] },
  tip: '근력 저하·감각 소실이 진행하거나 보행 이상·손 서투름이 생기면 즉시 알리도록 기준을 정해 준다. 의뢰 기준을 미리 정해 두는 것도 처방의 일부다.' },

// ══════════════════════════════════════════════════════════════
// p15 신동혁 — 방사통 동반 허리통증
// ══════════════════════════════════════════════════════════════
'p15:t1': { proto: 'mdt',
  best: { direction: 'extension', criteria: 'centralize', volume: 'r10', sched: 'q2h', monitor: 'peripheralize', posture: 'lordosis' },
  ok: { volume: ['r5'], sched: ['tid'] },
  tip: 'CPG 근거등급 A. 방사통이 있을 때 중심화 여부가 예후를 가장 잘 예측한다. 다리로 증상이 번지면 즉시 멈추고 방향을 다시 찾는다.' },
'p15:t2': { proto: 'traction',
  best: { region: 'lumb_prone', mode: 'intermittent', force: 'f25', time: 't15', combine: 'with_ex', sched: 'w23' },
  ok: { region: ['lumb_sup'], mode: ['static'], force: ['f50'], time: ['t10', 't20'], sched: ['w35'] },
  tip: '허리 견인은 방사통이 있는 하위군에서만 제한적으로 고려된다(권고등급 C). 반드시 운동과 병행하며, 방사통 없는 허리통증에는 CPG 비권고다.' },
'p15:t3': { proto: 'neural_mob',
  best: { target: 'sciatic', technique: 'slider', range: 'symptom_free', dose: 'r10x3', sched: 'daily_home' },
  ok: { target: ['femoral'], technique: ['prox_first'], range: ['onset'], dose: ['r30'], sched: ['w23'] },
  tip: '슬라이더부터 저강도로. 신경 증상 재현을 목표로 삼으면 오히려 증상이 악화된다.' },
'p15:t4': { proto: 'mdt',
  best: { direction: 'lateral', criteria: 'centralize', volume: 'r10', sched: 'q2h', monitor: 'peripheralize', posture: 'lordosis' },
  ok: { direction: ['extension'], volume: ['r5'], sched: ['tid'] },
  tip: '가쪽 이동(lateral shift)이 있으면 먼저 교정한 뒤 폄 방향으로 진행한다. 교정 없이 폄만 반복하면 증상이 잘 줄지 않는다.' },
'p15:t5': { proto: 'education',
  best: { content: 'self_monitor', frame: 'reassure_active', method: 'verbal_written', behavior: 'goal_setting', reinforce: 'each_visit' },
  ok: { content: ['prognosis', 'stay_active'], method: ['demo'], behavior: ['load_mgmt'] },
  tip: '말총증후군 징후(안장 감각 저하, 대소변 장애, 양측 다리 위약)를 환자가 스스로 감시할 수 있게 알려 주는 것이 방사통 환자 교육의 필수 항목이다.' },
'p15:t6': { proto: 'joint_mob',
  best: { target: 'l45', grade: 'g3', position: 'mid', dose: 'osc30', response: 'pain_limit', sched: 'w23_4' },
  ok: { target: ['tl', 'l13'], grade: ['g2', 'g4'], position: ['resting'], response: ['reassess'] },
  tip: '신경 자극을 피하며 비추력 가동술로 접근한다. 방사통이 늘어나면 즉시 중단하는 것이 추력 교정 대신 가동술을 고르는 이유다.' },
'p15:t7': { proto: 'motor_control',
  best: { target: 'multifidus', feedback: 'biofeedback', intensity: 'low', volume: 'h10x10', progress: 'to_function', sched: 'daily' },
  ok: { target: ['tra', 'ext'], feedback: ['tactile'], volume: ['h5x10x3'], sched: ['w35'] },
  tip: 'CPG 근거등급 A이지만 도입 시점이 중요하다 — 증상이 안정되고 중심화가 이뤄진 뒤에 점진적으로 넣는다.' },
'p15:t8': { proto: 'gait_train',
  best: { task: 'lift', assist: 'independent', load: 'fwb', volume: 'v3x10', sched: 'w23' },
  ok: { task: ['bend', 'sit_stand'], volume: ['distance'], sched: ['w35'] },
  tip: '들기 방법과 작업대 높이를 실제 업무 조건에 맞춰 조정하고, 복귀 일정을 단계로 나눠 문서화한다.' },

// ══════════════════════════════════════════════════════════════
// p16 하유리 — 움직임 조절 장애 동반 허리통증 (간호사)
// ══════════════════════════════════════════════════════════════
'p16:t1': { proto: 'motor_control',
  best: { target: 'multifidus', feedback: 'biofeedback', intensity: 'low', volume: 'h10x10', progress: 'to_function', sched: 'daily' },
  ok: { target: ['tra'], feedback: ['tactile', 'mirror'], volume: ['h5x10x3'], sched: ['w35'] },
  tip: 'CPG 근거등급 A — 이 범주의 핵심 중재. 뭇갈래근·배가로근의 분리 활성화에서 시작해 반드시 기능적 통합까지 진행해야 한다.' },
'p16:t2': { proto: 'motor_control',
  best: { target: 'tra', feedback: 'mirror', intensity: 'low', volume: 'h5x10x3', progress: 'to_function', sched: 'daily' },
  ok: { target: ['multifidus', 'glute'], feedback: ['tactile', 'biofeedback'], intensity: ['mid'], sched: ['w35'] },
  tip: '증상을 만드는 동작(굽혔다 펴기·환자 이송)을 그대로 재교육 과제로 삼는다. 중립 자세를 "유지"하는 것이 아니라 조절하며 움직이게 하는 것이 목표다.' },
'p16:t3': { proto: 'education',
  best: { content: 'stay_active', frame: 'reassure_active', method: 'verbal_written', behavior: 'goal_setting', reinforce: 'each_visit' },
  ok: { content: ['prognosis', 'load_mgmt'], method: ['demo'], behavior: ['ergonomic'] },
  tip: '재발이 곧 악화가 아니라는 점, 한 자세를 오래 지키기보다 자주 바꾸는 것이 낫다는 점을 능동 대처의 틀로 전달한다.' },
'p16:t4': { proto: 'gait_train',
  best: { task: 'transfer', assist: 'independent', load: 'fwb', volume: 'v3x10', sched: 'w23' },
  ok: { task: ['lift', 'bend'], assist: ['aid'], volume: ['v10min', 'distance'], sched: ['w35'] },
  tip: '간호사의 환자 이송·체위 변경 동작에 몸통 조절을 실제로 얹어 본다. 치료실 운동이 근무 동작으로 옮겨 가야 재발이 줄어든다.' },
'p16:t5': { proto: 'aerobic',
  best: { mode: 'walk', intensity: 'i40', time: 't30', sched: 'w35' },
  ok: { mode: ['bike', 'aqua'], intensity: ['rpe', 'i60'], time: ['t10'], sched: ['w5'] },
  tip: 'CPG 근거등급 A. 환자가 이미 편해하는 활동(걷기)을 골라야 지속된다. 강도보다 꾸준함이 중요하다.' },
'p16:t6': { proto: 'joint_mob',
  best: { target: 'tl', grade: 'g3', position: 'mid', dose: 'osc30', response: 'reassess', sched: 'w23_4' },
  ok: { target: ['l13', 'hip', 'si'], grade: ['g2', 'g4'], position: ['resting'] },
  tip: '움직임 조절 장애 범주에서 도수치료는 보조일 뿐이다. 이미 과가동인 L4-5가 아니라 인접한 저가동 분절에만 제한적으로 쓴다.' },

// ══════════════════════════════════════════════════════════════
// p17 양준서 — 안쪽곁인대(MCL) 2도 손상
// ══════════════════════════════════════════════════════════════
'p17:t1': { proto: 'rom_ex',
  best: { target: 'tf_ext', assist: 'active', range: 'to_onset', volume: 'v10x3', sched: 'tid' },
  ok: { target: ['tf_flex', 'patella'], assist: ['aarom'], range: ['painfree'], volume: ['hold'], sched: ['daily'] },
  tip: 'CPG 근거등급 A — 통증 허용 범위 내에서 즉시 체중부하와 가동을 시작한다. 2도 MCL은 고정하지 않고 움직일 때 더 잘 낫는다.' },
'p17:t2': { proto: 'orthosis',
  best: { device: 'hinged', position: 'functional', wear: 'day_task', period: 'p1_3m', combine: 'with_ex' },
  ok: { device: ['functional_acl'], position: ['protective'], wear: ['full'], period: ['p2w'] },
  tip: '경첩형 보조기는 가쪽(외반) 부하는 막고 굽힘·폄은 허용한다. 완전 고정 장치와 목적이 정반대라는 점이 요점이다.' },
'p17:t3': { proto: 'strength',
  best: { target: 'quad', mode: 'isometric', load: 'bw', volume: 'iso10', rest: 'r60', sched: 'w35', progress: 'pain_rule' },
  ok: { target: ['ham', 'hip_post'], mode: ['closed_chain', 'isotonic'], load: ['l40', 'l60'], volume: ['v3x10', 'v3x15'], sched: ['w23', 'daily'], progress: ['rep_rule'] },
  tip: '등척성으로 시작해 통증 반응을 보며 폐쇄사슬로 넘어간다. 급성기 열린사슬 무릎 폄은 외반 부하를 키울 수 있다.' },
'p17:t4': { proto: 'balance',
  best: { base: 'single_firm', vision: 'eyes_open', task: 'static', volume: 'v30x3', sched: 'daily_4w' },
  ok: { base: ['single_foam', 'dynamic'], vision: ['eyes_closed', 'head_move'], task: ['reach', 'perturb', 'sport'], volume: ['v10min'], sched: ['w35_6'] },
  tip: '균형·고유수용성에서 시작해 방향전환까지 단계적으로 올린다. 스키 복귀에는 회전 부하에 대한 조절이 반드시 포함돼야 한다.' },
'p17:t5': { proto: 'cryo',
  best: { agent: 'icepack', time: 't15', combine: 'compress_elev', sched: 'q2h' },
  ok: { agent: ['cryo_cuff'], time: ['t10'], combine: ['motion'], sched: ['tid', 'post_ex'] },
  tip: '급성기 통증·부종 관리 보조. 냉각 때문에 조기 체중부하와 가동을 미루면 본말이 뒤바뀐다.' },
'p17:t6': { proto: 'plyometric',
  best: { stage: 'unilateral', cue: 'quality_feedback', volume: 'v3x8', rest: 'r120', sched: 'w23_6', criteria: 'lsi90' },
  ok: { stage: ['bilateral', 'multiplanar', 'sport'], volume: ['contacts'], rest: ['r60'], criteria: [] },
  tip: '복귀 기준을 근력 대칭성·한발뛰기 배터리·IKDC로 정해 두고 통과 여부로 판단한다. 통증만 없다고 복귀시키면 재손상 위험이 크다.' },
'p17:t7': { proto: 'education',
  best: { content: 'prognosis', frame: 'reassure_active', method: 'verbal_written', behavior: 'goal_setting', reinforce: 'each_visit' },
  ok: { content: ['stay_active', 'load_mgmt'], method: ['demo'], behavior: ['load_mgmt'] },
  tip: '2도 MCL은 예후가 좋다는 점과, 그럼에도 조기 복귀가 재손상을 부른다는 점을 함께 전달하고 단계별 목표를 문서로 준다.' },

// ══════════════════════════════════════════════════════════════
// p18 구세라 — 만성 발목 불안정성 (CAI)
// ══════════════════════════════════════════════════════════════
'p18:t1': { proto: 'balance',
  best: { base: 'single_foam', vision: 'eyes_closed', task: 'perturb', volume: 'v30x3', sched: 'daily_4w' },
  ok: { base: ['single_firm', 'dynamic'], vision: ['eyes_open', 'head_move'], task: ['static', 'reach', 'sport'], volume: ['v10min'], sched: ['w35_6'] },
  tip: 'CPG 근거등급 A — 만성 발목 불안정성의 일차 중재. 한발서기 → 불안정 지지면 → 동적 과제로 올리되, 지지면·시각·과제 중 한 번에 하나씩만 어렵게 한다.' },
'p18:t2': { proto: 'strength',
  best: { target: 'peroneal', mode: 'isotonic', load: 'l40', volume: 'v3x15', rest: 'r30', sched: 'w35', progress: 'rep_rule' },
  ok: { target: ['tib_ant', 'triceps', 'hip_prox'], mode: ['closed_chain', 'eccentric'], load: ['l60', 'bw'], volume: ['v3x10'], rest: ['r60'], sched: ['w23', 'daily'], progress: ['pain_rule'] },
  tip: '종아리근의 근력만이 아니라 반응속도(발목이 안쪽으로 꺾일 때 얼마나 빨리 붙잡는가)를 함께 훈련해야 CAI가 개선된다.' },
'p18:t3': { proto: 'joint_mob',
  best: { target: 'talus_post', grade: 'g3', position: 'end', dose: 'osc30', response: 'reassess', sched: 'w23_4' },
  ok: { target: ['fibula', 'subtalar'], grade: ['g4', 'g2'], position: ['mid'], dose: ['osc60'] },
  tip: '만성기에는 급성기와 반대로 목말뼈 뒤쪽 활주를 쓴다 — 발등굽힘 제한을 푸는 방향이다. 자극성이 낮으므로 끝범위 Ⅲ·Ⅳ등급이 가능하다.' },
'p18:t4': { proto: 'orthosis',
  best: { device: 'lace_brace', position: 'neutral', wear: 'day_task', period: 'p1_3m', combine: 'with_ex' },
  ok: { device: ['semi_rigid', 'tape'], wear: ['full'], period: ['p6m'] },
  tip: '보조기·테이핑은 재손상을 실제로 줄인다. 다만 운동 없이 보조기만 처방하면 불안정성 자체는 그대로 남는다 — 반드시 운동과 함께.' },
'p18:t5': { proto: 'education',
  best: { content: 'ergonomic', frame: 'reassure_active', method: 'demo', behavior: 'ergonomic', reinforce: 'each_visit' },
  ok: { content: ['load_mgmt', 'self_monitor'], method: ['verbal_written'], behavior: ['load_mgmt'] },
  tip: '근무 중 굽 낮추기, 사다리 작업 시 지지 전략처럼 실제 환경 조건을 바꾼다. 재손상 기전을 아는 것이 회피가 아니라 조절로 이어진다.' },
'p18:t6': { proto: 'gait_train',
  best: { task: 'hike', assist: 'independent', load: 'fwb', volume: 'distance', sched: 'w35' },
  ok: { task: ['run_jump', 'balance', 'stairs'], volume: ['v10min', 'v3x10'], sched: ['w23'] },
  tip: '회피해 온 활동(등산·러닝)으로 단계적으로 노출한다. 두려움 때문에 안 하던 활동을 되돌리는 것이 CAI 재활의 목표다.' },
'p18:t7': { proto: 'education',
  best: { content: 'prognosis', frame: 'reassure_active', method: 'verbal_written', behavior: 'goal_setting', reinforce: 'each_visit' },
  ok: { content: ['exercise_why', 'stay_active'], method: ['demo'] },
  tip: '"발목이 원래 약한 체질"이 아니라 훈련으로 개선되는 상태임을 설명한다. 예후에 대한 인식이 운동 순응을 좌우한다.' },
'p18:t8': { proto: 'education',
  best: { content: 'self_monitor', frame: 'reassure_active', method: 'verbal_written', behavior: 'goal_setting', reinforce: 'each_visit' },
  ok: { content: ['exercise_why'], method: ['demo'] },
  tip: 'FAAM·CAIT를 일정 간격으로 다시 측정해 중재 반응을 확인한다. 만성 상태일수록 변화가 느려 객관적 지표가 없으면 방향을 잃는다.' },

// ══════════════════════════════════════════════════════════════
// p19 표민아 — 비관절염성 엉덩관절통 · 이형성/미세불안정 (무용수)
// ══════════════════════════════════════════════════════════════
'p19:t1': { proto: 'motor_control',
  best: { target: 'trunk', feedback: 'mirror', intensity: 'low', volume: 'h5x10x3', progress: 'to_function', sched: 'daily' },
  ok: { target: ['abd', 'ext_rot'], feedback: ['tactile', 'biofeedback'], intensity: ['mid'], sched: ['w35'] },
  tip: '과가동 관절은 근육 조절로 안정을 얻는다. 한 다리 지지에서 골반이 떨어지지 않게 하는 훈련이 무용 동작의 토대가 된다.' },
'p19:t2': { proto: 'strength',
  best: { target: 'abd', mode: 'isotonic', load: 'l60', volume: 'v3x10', rest: 'r60', sched: 'w23', progress: 'rep_rule' },
  ok: { target: ['ext_rot', 'glute_max', 'trunk'], mode: ['closed_chain'], load: ['l40', 'l80'], volume: ['v3x15'], sched: ['w35'], progress: ['pain_rule'] },
  tip: '벌림근과 깊은 가쪽돌림근이 넙다리뼈 머리를 관절오목 안에 잡아 준다. 이형성·미세불안정 하위군에서 근력이 곧 안정화 장치다.' },
'p19:t3': { proto: 'education',
  best: { content: 'load_mgmt', frame: 'reassure_active', method: 'demo', behavior: 'load_mgmt', reinforce: 'each_visit' },
  ok: { content: ['exercise_why', 'prognosis'], method: ['verbal_written'], behavior: ['goal_setting'] },
  tip: '무용수는 "더 늘리면 나아진다"고 믿는다. 이미 과가동인 관절에서 스트레칭을 늘리는 것이 문제를 키운다는 점을 직접 시연으로 이해시켜야 행동이 바뀐다.' },
'p19:t4': { proto: 'education',
  best: { content: 'load_mgmt', frame: 'reassure_active', method: 'verbal_written', behavior: 'load_mgmt', reinforce: 'each_visit' },
  ok: { content: ['ergonomic', 'stay_active'], method: ['demo'], behavior: ['goal_setting'] },
  tip: '끝범위 동작의 빈도와 유지 시간, 연습량 분배를 구체적 숫자로 조절한다. 연습을 끊는 것이 아니라 배분을 바꾸는 것이다.' },
'p19:t5': { proto: 'aquatic',
  best: { depth: 'chest', temp: 't30', content: 'walk', time: 't30', sched: 'w23' },
  ok: { depth: ['waist', 'neck'], temp: ['t34'], content: ['resist', 'rom'], time: ['t20'], sched: ['w1', 'w35'] },
  tip: '부력으로 관절 부하를 덜면서 한 다리 지지·몸통 조절을 훈련한다. 이완이 목적이 아니라 능동 조절 훈련이므로 수온은 활동적인 범위로 잡는다.' },
'p19:t6': { proto: 'gait_train',
  best: { task: 'dance', assist: 'independent', load: 'fwb', volume: 'distance', sched: 'w23' },
  ok: { task: ['single_leg', 'squat'], volume: ['v3x10', 'v10min'], sched: ['w35'] },
  tip: '아라베스크·피루엣을 동작 단위로 쪼개 재교육하고 다시 조립한다. 무용 특이적 과제 없이는 연습 복귀가 성립하지 않는다.' },
'p19:t7': { proto: 'education',
  best: { content: 'self_monitor', frame: 'reassure_active', method: 'verbal_written', behavior: 'goal_setting', reinforce: 'each_visit' },
  ok: { content: ['exercise_why', 'prognosis'], method: ['demo'] },
  tip: 'iHOT-33·HOS를 일정 간격으로 재측정해 반응을 추적한다. 무용수의 주관적 수행 만족도는 근력 수치만으로는 잡히지 않는다.' },
'p19:t8': { proto: 'referral',
  best: { to: 'ortho', reason: 'decision', timing: 'after_trial', pt_plan: 'continue' },
  ok: { to: ['surgeon'], reason: ['imaging', 'nonresponse'], timing: ['concurrent'] },
  tip: '이형성 확진과 수술 상담은 영상(MRA)이 필요하다. 다만 보존치료를 충분히 해 본 뒤 의뢰하는 것이 순서이며, 의뢰 후에도 운동은 이어 간다.' },
};
